language: cpp
# safelist
# branches:
#   only:
#   - master
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libgtest-dev -y
- cd /usr/src/gtest
- sudo env "PATH=$PATH" cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
before_install:
# C++17
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
# Install dependencies
install: 
# C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
#doxygen
  - sudo apt-get install doxygen
  - sudo apt-get install graphviz
# Install dependencies
# addons:
#   apt:
#     packages:
#       - doxygen
script:
#try to know gcc version  
- gcc --version
- cd $TRAVIS_BUILD_DIR && mkdir build && cd build
- cmake ..
- cmake --build .
- cmake --build . --target package
- cmake --build . --target doc_doxygen
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -v --fail --show-error -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ua8a3:$BINTRAY_API_KEY "https://api.bintray.com/content/fakecompany/otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: $TRAVIS_BUILD_DIR/build/html
    verbose: true
